name: ondemand_terminal
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dart_console: ^1.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  ondemand:
    git: https://github.com/RubbaBoy/ondemand
#  path: ^1.7.0

dependency_overrides:
  ondemand:
    path: E:/ondemand

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
